#include "data.h"

LedCommand ledCommands[50] = {
    LED_GREEN, LED_RED, LED_BLINK, LED_BLUE, LED_GREEN,
    LED_RED, LED_BLINK, LED_GREEN, LED_BLUE, LED_RED,
    LED_BLINK, LED_GREEN, LED_BLUE, LED_RED, LED_GREEN,
    LED_BLINK, LED_BLUE, LED_RED, LED_GREEN, LED_BLINK,
    LED_BLUE, LED_RED, LED_GREEN, LED_BLINK, LED_BLUE,
    LED_RED, LED_GREEN, LED_BLINK, LED_BLUE, LED_RED,
    LED_GREEN, LED_BLINK, LED_BLUE, LED_RED, LED_GREEN,
    LED_BLINK, LED_BLUE, LED_RED, LED_GREEN, LED_BLINK,
    LED_BLUE, LED_RED, LED_GREEN, LED_BLINK, LED_BLUE,
    LED_RED, LED_GREEN, LED_BLINK, LED_BLUE, LED_RED
};

LedCommand randomCommand() {
    return ledCommands[random(0, 50)];
}